// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

#ifndef PROTOBUF_Protocol_2eproto__INCLUDED
#define PROTOBUF_Protocol_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Protocol_2eproto();
void protobuf_AssignDesc_Protocol_2eproto();
void protobuf_ShutdownFile_Protocol_2eproto();

class GnuplotMessage;

// ===================================================================

class GnuplotMessage : public ::google::protobuf::Message {
 public:
  GnuplotMessage();
  virtual ~GnuplotMessage();
  
  GnuplotMessage(const GnuplotMessage& from);
  
  inline GnuplotMessage& operator=(const GnuplotMessage& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const GnuplotMessage& default_instance();
  
  void Swap(GnuplotMessage* other);
  
  // implements Message ----------------------------------------------
  
  GnuplotMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GnuplotMessage& from);
  void MergeFrom(const GnuplotMessage& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional string processname = 1;
  inline bool has_processname() const;
  inline void clear_processname();
  static const int kProcessnameFieldNumber = 1;
  inline const ::std::string& processname() const;
  inline void set_processname(const ::std::string& value);
  inline void set_processname(const char* value);
  inline void set_processname(const char* value, size_t size);
  inline ::std::string* mutable_processname();
  
  // optional uint32 pid = 2;
  inline bool has_pid() const;
  inline void clear_pid();
  static const int kPidFieldNumber = 2;
  inline ::google::protobuf::uint32 pid() const;
  inline void set_pid(::google::protobuf::uint32 value);
  
  // optional double userCpuLoad = 3;
  inline bool has_usercpuload() const;
  inline void clear_usercpuload();
  static const int kUserCpuLoadFieldNumber = 3;
  inline double usercpuload() const;
  inline void set_usercpuload(double value);
  
  // optional double systemCpuLoad = 4;
  inline bool has_systemcpuload() const;
  inline void clear_systemcpuload();
  static const int kSystemCpuLoadFieldNumber = 4;
  inline double systemcpuload() const;
  inline void set_systemcpuload(double value);
  
  // optional double systemCpuUtilization = 5;
  inline bool has_systemcpuutilization() const;
  inline void clear_systemcpuutilization();
  static const int kSystemCpuUtilizationFieldNumber = 5;
  inline double systemcpuutilization() const;
  inline void set_systemcpuutilization(double value);
  
  // optional double userCpuUtilization = 6;
  inline bool has_usercpuutilization() const;
  inline void clear_usercpuutilization();
  static const int kUserCpuUtilizationFieldNumber = 6;
  inline double usercpuutilization() const;
  inline void set_usercpuutilization(double value);
  
  // optional double memoryUtilization = 7;
  inline bool has_memoryutilization() const;
  inline void clear_memoryutilization();
  static const int kMemoryUtilizationFieldNumber = 7;
  inline double memoryutilization() const;
  inline void set_memoryutilization(double value);
  
  // optional uint32 networkInBytes = 8;
  inline bool has_networkinbytes() const;
  inline void clear_networkinbytes();
  static const int kNetworkInBytesFieldNumber = 8;
  inline ::google::protobuf::uint32 networkinbytes() const;
  inline void set_networkinbytes(::google::protobuf::uint32 value);
  
  // optional uint32 networkOutBytes = 9;
  inline bool has_networkoutbytes() const;
  inline void clear_networkoutbytes();
  static const int kNetworkOutBytesFieldNumber = 9;
  inline ::google::protobuf::uint32 networkoutbytes() const;
  inline void set_networkoutbytes(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:GnuplotMessage)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::std::string* processname_;
  static const ::std::string _default_processname_;
  ::google::protobuf::uint32 pid_;
  double usercpuload_;
  double systemcpuload_;
  double systemcpuutilization_;
  double usercpuutilization_;
  double memoryutilization_;
  ::google::protobuf::uint32 networkinbytes_;
  ::google::protobuf::uint32 networkoutbytes_;
  friend void  protobuf_AddDesc_Protocol_2eproto();
  friend void protobuf_AssignDesc_Protocol_2eproto();
  friend void protobuf_ShutdownFile_Protocol_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(9 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static GnuplotMessage* default_instance_;
};
// ===================================================================


// ===================================================================

// GnuplotMessage

// optional string processname = 1;
inline bool GnuplotMessage::has_processname() const {
  return _has_bit(0);
}
inline void GnuplotMessage::clear_processname() {
  if (processname_ != &_default_processname_) {
    processname_->clear();
  }
  _clear_bit(0);
}
inline const ::std::string& GnuplotMessage::processname() const {
  return *processname_;
}
inline void GnuplotMessage::set_processname(const ::std::string& value) {
  _set_bit(0);
  if (processname_ == &_default_processname_) {
    processname_ = new ::std::string;
  }
  processname_->assign(value);
}
inline void GnuplotMessage::set_processname(const char* value) {
  _set_bit(0);
  if (processname_ == &_default_processname_) {
    processname_ = new ::std::string;
  }
  processname_->assign(value);
}
inline void GnuplotMessage::set_processname(const char* value, size_t size) {
  _set_bit(0);
  if (processname_ == &_default_processname_) {
    processname_ = new ::std::string;
  }
  processname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* GnuplotMessage::mutable_processname() {
  _set_bit(0);
  if (processname_ == &_default_processname_) {
    processname_ = new ::std::string;
  }
  return processname_;
}

// optional uint32 pid = 2;
inline bool GnuplotMessage::has_pid() const {
  return _has_bit(1);
}
inline void GnuplotMessage::clear_pid() {
  pid_ = 0u;
  _clear_bit(1);
}
inline ::google::protobuf::uint32 GnuplotMessage::pid() const {
  return pid_;
}
inline void GnuplotMessage::set_pid(::google::protobuf::uint32 value) {
  _set_bit(1);
  pid_ = value;
}

// optional double userCpuLoad = 3;
inline bool GnuplotMessage::has_usercpuload() const {
  return _has_bit(2);
}
inline void GnuplotMessage::clear_usercpuload() {
  usercpuload_ = 0;
  _clear_bit(2);
}
inline double GnuplotMessage::usercpuload() const {
  return usercpuload_;
}
inline void GnuplotMessage::set_usercpuload(double value) {
  _set_bit(2);
  usercpuload_ = value;
}

// optional double systemCpuLoad = 4;
inline bool GnuplotMessage::has_systemcpuload() const {
  return _has_bit(3);
}
inline void GnuplotMessage::clear_systemcpuload() {
  systemcpuload_ = 0;
  _clear_bit(3);
}
inline double GnuplotMessage::systemcpuload() const {
  return systemcpuload_;
}
inline void GnuplotMessage::set_systemcpuload(double value) {
  _set_bit(3);
  systemcpuload_ = value;
}

// optional double systemCpuUtilization = 5;
inline bool GnuplotMessage::has_systemcpuutilization() const {
  return _has_bit(4);
}
inline void GnuplotMessage::clear_systemcpuutilization() {
  systemcpuutilization_ = 0;
  _clear_bit(4);
}
inline double GnuplotMessage::systemcpuutilization() const {
  return systemcpuutilization_;
}
inline void GnuplotMessage::set_systemcpuutilization(double value) {
  _set_bit(4);
  systemcpuutilization_ = value;
}

// optional double userCpuUtilization = 6;
inline bool GnuplotMessage::has_usercpuutilization() const {
  return _has_bit(5);
}
inline void GnuplotMessage::clear_usercpuutilization() {
  usercpuutilization_ = 0;
  _clear_bit(5);
}
inline double GnuplotMessage::usercpuutilization() const {
  return usercpuutilization_;
}
inline void GnuplotMessage::set_usercpuutilization(double value) {
  _set_bit(5);
  usercpuutilization_ = value;
}

// optional double memoryUtilization = 7;
inline bool GnuplotMessage::has_memoryutilization() const {
  return _has_bit(6);
}
inline void GnuplotMessage::clear_memoryutilization() {
  memoryutilization_ = 0;
  _clear_bit(6);
}
inline double GnuplotMessage::memoryutilization() const {
  return memoryutilization_;
}
inline void GnuplotMessage::set_memoryutilization(double value) {
  _set_bit(6);
  memoryutilization_ = value;
}

// optional uint32 networkInBytes = 8;
inline bool GnuplotMessage::has_networkinbytes() const {
  return _has_bit(7);
}
inline void GnuplotMessage::clear_networkinbytes() {
  networkinbytes_ = 0u;
  _clear_bit(7);
}
inline ::google::protobuf::uint32 GnuplotMessage::networkinbytes() const {
  return networkinbytes_;
}
inline void GnuplotMessage::set_networkinbytes(::google::protobuf::uint32 value) {
  _set_bit(7);
  networkinbytes_ = value;
}

// optional uint32 networkOutBytes = 9;
inline bool GnuplotMessage::has_networkoutbytes() const {
  return _has_bit(8);
}
inline void GnuplotMessage::clear_networkoutbytes() {
  networkoutbytes_ = 0u;
  _clear_bit(8);
}
inline ::google::protobuf::uint32 GnuplotMessage::networkoutbytes() const {
  return networkoutbytes_;
}
inline void GnuplotMessage::set_networkoutbytes(::google::protobuf::uint32 value) {
  _set_bit(8);
  networkoutbytes_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Protocol_2eproto__INCLUDED
