// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

#ifndef PROTOBUF_Protocol_2eproto__INCLUDED
#define PROTOBUF_Protocol_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Protocol_2eproto();
void protobuf_AssignDesc_Protocol_2eproto();
void protobuf_ShutdownFile_Protocol_2eproto();

class ProcessCollectorMessage;
class ProcessesMessage_ProcessMessage;

// ===================================================================

class ProcessesMessage_ProcessMessage : public ::google::protobuf::Message {
 public:
  ProcessesMessage_ProcessMessage();
  virtual ~ProcessesMessage_ProcessMessage();
  
  ProcessesMessage_ProcessMessage(const ProcessesMessage_ProcessMessage& from);
  
  inline ProcessesMessage_ProcessMessage& operator=(const ProcessesMessage_ProcessMessage& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ProcessesMessage_ProcessMessage& default_instance();
  
  void Swap(ProcessesMessage_ProcessMessage* other);
  
  // implements Message ----------------------------------------------
  
  ProcessesMessage_ProcessMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProcessesMessage_ProcessMessage& from);
  void MergeFrom(const ProcessesMessage_ProcessMessage& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string processname = 1;
  inline bool has_processname() const;
  inline void clear_processname();
  static const int kProcessnameFieldNumber = 1;
  inline const ::std::string& processname() const;
  inline void set_processname(const ::std::string& value);
  inline void set_processname(const char* value);
  inline void set_processname(const char* value, size_t size);
  inline ::std::string* mutable_processname();
  
  // required uint32 pid = 2;
  inline bool has_pid() const;
  inline void clear_pid();
  static const int kPidFieldNumber = 2;
  inline ::google::protobuf::uint32 pid() const;
  inline void set_pid(::google::protobuf::uint32 value);
  
  // required double userCpuLoad = 3;
  inline bool has_usercpuload() const;
  inline void clear_usercpuload();
  static const int kUserCpuLoadFieldNumber = 3;
  inline double usercpuload() const;
  inline void set_usercpuload(double value);
  
  // required double systemCpuLoad = 4;
  inline bool has_systemcpuload() const;
  inline void clear_systemcpuload();
  static const int kSystemCpuLoadFieldNumber = 4;
  inline double systemcpuload() const;
  inline void set_systemcpuload(double value);
  
  // @@protoc_insertion_point(class_scope:ProcessesMessage.ProcessMessage)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::std::string* processname_;
  static const ::std::string _default_processname_;
  ::google::protobuf::uint32 pid_;
  double usercpuload_;
  double systemcpuload_;
  friend void  protobuf_AddDesc_Protocol_2eproto();
  friend void protobuf_AssignDesc_Protocol_2eproto();
  friend void protobuf_ShutdownFile_Protocol_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static ProcessesMessage_ProcessMessage* default_instance_;
};
// -------------------------------------------------------------------

class ProcessCollectorMessage : public ::google::protobuf::Message {
 public:
  ProcessCollectorMessage();
  virtual ~ProcessCollectorMessage();
  
  ProcessCollectorMessage(const ProcessCollectorMessage& from);
  
  inline ProcessCollectorMessage& operator=(const ProcessCollectorMessage& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ProcessCollectorMessage& default_instance();
  
  void Swap(ProcessCollectorMessage* other);
  
  // implements Message ----------------------------------------------
  
  ProcessCollectorMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProcessCollectorMessage& from);
  void MergeFrom(const ProcessCollectorMessage& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef ProcessesMessage_ProcessMessage ProcessMessage;
  
  // accessors -------------------------------------------------------
  
  // repeated .ProcessesMessage.ProcessMessage processmessage = 1;
  inline int processmessage_size() const;
  inline void clear_processmessage();
  static const int kProcessmessageFieldNumber = 1;
  inline const ::ProcessesMessage_ProcessMessage& processmessage(int index) const;
  inline ::ProcessesMessage_ProcessMessage* mutable_processmessage(int index);
  inline ::ProcessesMessage_ProcessMessage* add_processmessage();
  inline const ::google::protobuf::RepeatedPtrField< ::ProcessesMessage_ProcessMessage >&
      processmessage() const;
  inline ::google::protobuf::RepeatedPtrField< ::ProcessesMessage_ProcessMessage >*
      mutable_processmessage();
  
  // @@protoc_insertion_point(class_scope:ProcessesMessage)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::RepeatedPtrField< ::ProcessesMessage_ProcessMessage > processmessage_;
  friend void  protobuf_AddDesc_Protocol_2eproto();
  friend void protobuf_AssignDesc_Protocol_2eproto();
  friend void protobuf_ShutdownFile_Protocol_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static ProcessCollectorMessage* default_instance_;
};
// ===================================================================


// ===================================================================

// ProcessesMessage_ProcessMessage

// required string processname = 1;
inline bool ProcessesMessage_ProcessMessage::has_processname() const {
  return _has_bit(0);
}
inline void ProcessesMessage_ProcessMessage::clear_processname() {
  if (processname_ != &_default_processname_) {
    processname_->clear();
  }
  _clear_bit(0);
}
inline const ::std::string& ProcessesMessage_ProcessMessage::processname() const {
  return *processname_;
}
inline void ProcessesMessage_ProcessMessage::set_processname(const ::std::string& value) {
  _set_bit(0);
  if (processname_ == &_default_processname_) {
    processname_ = new ::std::string;
  }
  processname_->assign(value);
}
inline void ProcessesMessage_ProcessMessage::set_processname(const char* value) {
  _set_bit(0);
  if (processname_ == &_default_processname_) {
    processname_ = new ::std::string;
  }
  processname_->assign(value);
}
inline void ProcessesMessage_ProcessMessage::set_processname(const char* value, size_t size) {
  _set_bit(0);
  if (processname_ == &_default_processname_) {
    processname_ = new ::std::string;
  }
  processname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ProcessesMessage_ProcessMessage::mutable_processname() {
  _set_bit(0);
  if (processname_ == &_default_processname_) {
    processname_ = new ::std::string;
  }
  return processname_;
}

// required uint32 pid = 2;
inline bool ProcessesMessage_ProcessMessage::has_pid() const {
  return _has_bit(1);
}
inline void ProcessesMessage_ProcessMessage::clear_pid() {
  pid_ = 0u;
  _clear_bit(1);
}
inline ::google::protobuf::uint32 ProcessesMessage_ProcessMessage::pid() const {
  return pid_;
}
inline void ProcessesMessage_ProcessMessage::set_pid(::google::protobuf::uint32 value) {
  _set_bit(1);
  pid_ = value;
}

// required double userCpuLoad = 3;
inline bool ProcessesMessage_ProcessMessage::has_usercpuload() const {
  return _has_bit(2);
}
inline void ProcessesMessage_ProcessMessage::clear_usercpuload() {
  usercpuload_ = 0;
  _clear_bit(2);
}
inline double ProcessesMessage_ProcessMessage::usercpuload() const {
  return usercpuload_;
}
inline void ProcessesMessage_ProcessMessage::set_usercpuload(double value) {
  _set_bit(2);
  usercpuload_ = value;
}

// required double systemCpuLoad = 4;
inline bool ProcessesMessage_ProcessMessage::has_systemcpuload() const {
  return _has_bit(3);
}
inline void ProcessesMessage_ProcessMessage::clear_systemcpuload() {
  systemcpuload_ = 0;
  _clear_bit(3);
}
inline double ProcessesMessage_ProcessMessage::systemcpuload() const {
  return systemcpuload_;
}
inline void ProcessesMessage_ProcessMessage::set_systemcpuload(double value) {
  _set_bit(3);
  systemcpuload_ = value;
}

// -------------------------------------------------------------------

// ProcessesMessage

// repeated .ProcessesMessage.ProcessMessage processmessage = 1;
inline int ProcessCollectorMessage::processmessage_size() const {
  return processmessage_.size();
}
inline void ProcessCollectorMessage::clear_processmessage() {
  processmessage_.Clear();
}
inline const ::ProcessesMessage_ProcessMessage& ProcessCollectorMessage::processmessage(int index) const {
  return processmessage_.Get(index);
}
inline ::ProcessesMessage_ProcessMessage* ProcessCollectorMessage::mutable_processmessage(int index) {
  return processmessage_.Mutable(index);
}
inline ::ProcessesMessage_ProcessMessage* ProcessCollectorMessage::add_processmessage() {
  return processmessage_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ProcessesMessage_ProcessMessage >&
ProcessCollectorMessage::processmessage() const {
  return processmessage_;
}
inline ::google::protobuf::RepeatedPtrField< ::ProcessesMessage_ProcessMessage >*
ProcessCollectorMessage::mutable_processmessage() {
  return &processmessage_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Protocol_2eproto__INCLUDED
